### ISSUE TITLE
Cross Compilers Targeting i686 Linux Not Detected

### ISSUE THREAD

**Issue by grochoge** [AdaCore/gprconfig_kb#6]
To reproduce on Ubuntu 20.04:
1. sudo apt-get install gnat-10-i686-linux-gnu gprbuild
2. Run gprconfig
3. Cross-compiler target is not detected despite i686-linux-gnu-gnatls being in my path

I think `aarch64-linux-gnu-` could be changed to `.*-linux-gnu-` in compilers.xml and cross.xml to fix most of the issue?

**Comment by grochoge** [comment]
This appears to be fixed in the latest version (tried with GPRCONFIG 2023.0.0 (20230506))

**Comment by GuillermoHazebrouck** [comment]
It does not seem to be fully fixed yet. My gprbuild does not find the _aarch64-linux-gnu_ tool-chain when I declare it as target, while it really is in my PATH and functional. Calling _aarch64-linux-gnu-gnatmake_ works, so it really seems to be some bug or wrong configuration in gprbuild or gprconfig, because the toolchain does is not given in the list of compilers.
```
$ gprconfig --version
GPRCONFIG Pro 18.0w (19940713) (x86_64-linux-gnu)
```

The file compilers.xml contains no `aarch64-linux-gnu-` prefix, but `.*-linux-gnu-`
